### ISSUE TITLE
why does the svg pattern deviate from google/material-designs

### ISSUE THREAD

**Issue by claudia-a11y** [marella/material-design-icons#1]
i.e. action/label_outline/materialiconstwotone/

several icons are missing likely having different pattern is making harder to match what google has in latest

**Comment by marella** [comment]
This package only includes icons listed on https://fonts.google.com/icons. The icon `label_outline` might have been removed from that page as the `label` icon with `outlined` style is identical to it. It can be located at [`outlined/label.svg`](https://github.com/marella/material-design-icons/blob/main/svg/outlined/label.svg) in the current package.

With the current directory structure users don't have to remember the category name of an icon to find its path. For example, in official repo you need to know that `label` icon is part of `action` category to know its full path. But in the current repo you can locate it directly at `outlined/label.svg` or `two-tone/label.svg`. Also this way all SVG files are grouped by style. The [readme](https://github.com/marella/material-design-icons/tree/main/svg#usage) explains how to find the path of an icon. You can also search the icon name on [demo page](https://marella.me/material-design-icons/demo/svg/) and hover over the icon to see its path.

**Comment by claudia-a11y** [comment]
this was added in summer of 2020

material-design-icons/24px.svg at master · google/material-design-icons (github.com)<https://github.com/google/material-design-icons/blob/master/src/action/eco/materialicons/24px.svg>


searching for it on demo page doesn't come up your demo page but now I see it is not on fonts.google.com/icons it's SVG only

________________________________
