### ISSUE TITLE
missing icons

### ISSUE THREAD

**Issue by gasogassi** [marella/material-design-icons#17]
Missing [draft icon](https://fonts.google.com/icons?icon.query=draft) and perhaps some other icons, please do a repo update to include all icons.

**Comment by marella** [comment]
The icon posted above is from Material Symbols. This repo only has Material Icons which doesn't have [draft icon](https://fonts.google.com/icons?icon.query=draft&icon.set=Material+Icons).
For Material Symbols, please see [marella/material-symbols](https://github.com/marella/material-symbols).
