### ISSUE TITLE
Change the Weight that defines the symbol’s stroke weight <span>?

### ISSUE THREAD

**Issue by johnnytolengo** [marella/material-design-icons#18]
environment: Reactjs

How to change the weight of a given icon?

```
import '@material-design-icons/font';


<span className={`material-icons-outlined`} >home</span>
```

I already tried with font-weight: 100;  but nothing changes.

**Comment by marella** [comment]
Sorry for the late response. Material Icons don't have multiple weights but [Material Symbols](https://github.com/marella/material-symbols/tree/main/material-symbols#readme) have them.
