### ISSUE TITLE
Custom optical size

### ISSUE THREAD

**Issue by elitastic** [marella/material-design-icons#4]
Your scripts are awesome, but we would like to have an optical size other than 48px (20px).

Could we add an additional parameter to define an optical size just like you already added the "weight" param?

I could also assist you with a pull request if you want?

Thanks for a short feedback.

**Comment by marella** [comment]
Added `size` option in 0.4.2

**Comment by elitastic** [comment]
That was fast! 🚀🚀 Thank you very much! 👍
